### ISSUE TITLE
PHP Artisan Error

### ISSUE THREAD

**Issue by liveweb22** [updivision/estarter-ecommerce-for-laravel#10]
Hi, when i try to generate a key for Artisan, i get this error 

In KeyGenerateCommand.php line 96:

  file_get_contents(/var/www/html/estarter-ecommerce-for-laravel/.env): faile
  d to open stream: No such file or directory

**Comment by hanynasyr** [comment]
create an .env file. You can copy the co tents from sample.env file. then
try running the command again.

**Comment by paulduca** [comment]
@liveweb22 Do not forget to add these lines at the end of your .env file
```
ADMIN_ROLE_NAME=administrator
CLIENT_ROLE_NAME=client
```
