### ISSUE TITLE
Bug with clone product and images dropzone

### ISSUE THREAD

**Issue by Jimmylet** [updivision/estarter-ecommerce-for-laravel#14]
Hello,

I noticed a bug with the dropzone products. When I clone a product, they also duplicate the images of the dropzone. In the cloned product, when I delete these images, it deletes the files. Suddenly, the images of the original product no longer work.

Thanks for this project!

**Comment by paulduca** [comment]
Hello @Jimmylet,

Thank you for your interest in our project :)! 
For the moment we don't know when this will be fixed, but i wonder if you were able to manage to fix this, and why not, to make a pull request with it, or you can wait until we'll gonna fix it.

We plan to develop new features in the near future, so stay in tune :D.

Thanks,
Paul
