### ISSUE TITLE
Improve the dropzone field with descriptions and uptades

### ISSUE THREAD

**Issue by Jimmylet** [updivision/estarter-ecommerce-for-laravel#2]
Hello !

I test your work. This is a good way to see the practices implemented with Backpack. In addition, it is an excellent base for an e-commerce and for that, thank you!

Only, I have two three small improvements to offer for the future.

- Update to Laravel 5.5 and Backpack CRUD 3.3 and the latest version of Backpack Base (as long as we are there). Basically, with the new version, we have the possibility to manage several fields of our account as a user. It makes sense in an e-commerce, with the management of addresses etc.

- Improve the dropzone field. I really like how you did the gallery field and how you implemented it in the database. However, in my opinion, it misses the possibility of adding a "description" field. Describing an image can be important, especially for accessibility (the ALT field), or to specify some details.

I think ESTARTER-ecommerce is a very good base and I thank you for this work which teaches me a lot.

**Comment by paulduca** [comment]
Nice to meet you, Jimmylet!

Thanks for your kind words. It feels great to see that other developers appreciate our work. We put a few months in eStarter and counting.

**To answer your improvements requests:**
(1)  We are working on it.
(2) This is a very good idea. However, we are not sure when we will be able to implement it. But it will be awesome if you have the time to develop this feature for yourself and for the community. After all, this is open source and things will move much faster if people get involved. Of course, you will have our support.

Cheers!
PS: A release with new features is coming soon.

**Comment by Jimmylet** [comment]
@pduca Thank you very much for your response. I look forward to seeing the rest of the project!

**Comment by paulduca** [comment]
@Jimmylet Quick update: just lunched Laravel 5.5 & CRUD 3.3 support.
