### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by robertnicjoo** [updivision/estarter-ecommerce-for-laravel#3]
hi,

i just installed this on my local, and installed composer, generated key, run make:auth, seed etc. but i do not have access to admin panel.

any idea?

**Comment by hanynasyr** [comment]
What's the error you are getting?

**Comment by robertnicjoo** [comment]
404 Not Found
nginx/1.12.0

**Comment by paulduca** [comment]
@robertnicjoo What environment do you use?
btw - you don't need to run make:auth. Try installing it again without runnging this command, just simply run:
`$ composer install`
`$ php artisan key:generate`

setup your .env file, and then run
`$ php artisan migrate --seed`

**Comment by robertnicjoo** [comment]
@pduca  Local environment .

**Comment by robertnicjoo** [comment]
it's loading now, however it has error product_category in saving products and js error to show them.

thanks.

**Comment by hanynasyr** [comment]
I am getting the same error.
