### ISSUE TITLE
Attribute Edit

### ISSUE THREAD

**Issue by hanynasyr** [updivision/estarter-ecommerce-for-laravel#6]
There seems to be an error on Attribute edit page.

`ErrorException (E_ERROR)
count(): Parameter must be an array or an object that implements Countable (View: C:\xampp\htdocs\perkyadmin\resources\views\vendor\backpack\crud\fields\attribute_types.blade.php) (View: C:\xampp\htdocs\perkyadmin\resources\views\vendor\backpack\crud\fields\attribute_types.blade.php) (View: C:\xampp\htdocs\perkyadmin\resources\views\vendor\backpack\crud\fields\attribute_types.blade.php) (View: C:\xampp\htdocs\perkyadmin\resources\views\vendor\backpack\crud\fields\attribute_types.blade.php)`

**Comment by paulduca** [comment]
Hi @hanynasyr ,
I cannot replicate this error, can you give me more details about the steps that you're doing for this?

However, you can try looking into attribute_types.blade.php file and replace this:
```
@if (count(old('option')) >= 1)
```
with this:
```
@if (is_array(old('option')) && count(old('option')) > 0)
```

Let me now if it works.

Thank you,
Paul Duca

**Comment by hanynasyr** [comment]
Thanks. That solved the problem. but will I lose the changes when updating the repo?

**Comment by paulduca** [comment]
I will make an update in a few hours with those changes.

**Comment by hanynasyr** [comment]
Thanks a lot for the prompt and quick reply. Appreciate it

**Comment by paulduca** [comment]
fixed
