### ISSUE TITLE
Product Edit

### ISSUE THREAD

**Issue by hanynasyr** [updivision/estarter-ecommerce-for-laravel#7]
An error when editing products.
`ErrorException (E_ERROR)
count(): Parameter must be an array or an object that implements Countable (View: C:\xampp\htdocs\perkyadmin\resources\views\vendor\backpack\crud\fields\product_attributes.blade.php) (View: C:\xampp\htdocs\perkyadmin\resources\views\vendor\backpack\crud\fields\product_attributes.blade.php) (View: C:\xampp\htdocs\perkyadmin\resources\views\vendor\backpack\crud\fields\product_attributes.blade.php) (View: C:\xampp\htdocs\perkyadmin\resources\views\vendor\backpack\crud\fields\product_attributes.blade.php) (View: C:\xampp\htdocs\perkyadmin\resources\views\vendor\backpack\crud\fields\product_attributes.blade.php)`

**Comment by paulduca** [comment]
What version of PHP do you use?

In _resources\views\vendor\backpack\crud\fields\product_attributes.blade.php_, edit line '52' and replace this:
`@if(count(old('attributes')) > 0)`
with this:
`@if(is_array(old('attributes')) && count(old('attributes')) > 0)`

**Comment by hanynasyr** [comment]
PHP Version 7.2.1

**Comment by paulduca** [comment]
fixed
